accounts/urls.py
from django.urls import path, re_path, reverse, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views
from accounts.views import EditUserInfo

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name = 'logout'),
    path('register/', views.register, name = 'register'),
    path('profile/', views.view_profile, name = 'view_profile'),
    path('profile/edit/', views.edit_profile, name = 'edit_profile'),
    path('profile/edit/user_info', EditUserInfo.as_view(), name = 'edit_user_info'),
    path('change-password/', views.change_password, name = 'change_password'),
    
    path('reset-password/', PasswordResetView.as_view(
        template_name = 'accounts/reset_password.html',
        success_url = reverse_lazy('accounts:password_reset_done'),
        email_template_name = 'accounts/password_reset_email.html'), 
        name='password_reset'
    ),
    path('reset-password/done/', PasswordResetDoneView.as_view(
       template_name = 'accounts/password_reset_done.html', ), 
       name='password_reset_done'
    ),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name = 'accounts/password_reset_confirm.html', 
        success_url = reverse_lazy('accounts:password_reset_complete'),),
        name='password_reset_confirm'
    ),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(
        template_name = 'accounts/password_reset_complete.html', ), 
        name='password_reset_complete'
    ),

]

blog/urls.py
from django.urls import path

from blog.views import BlogHomeView,PublishPostView

app_name = 'blog'
urlpatterns = [
    path('', BlogHomeView.as_view(), name = 'blogHome'),
    path('publish/', PublishPostView.as_view(), name = 'publish_post'),
    
]

loginSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('account/', include('accounts.urls')),
    path('home/', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    profile_image = models.ImageField(upload_to = 'profile_image', blank = True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])

post_save.connect(create_profile, sender = User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    UserCreationForm, 
    UserChangeForm,
)

from accounts.models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
    def save(self, commit = True):
        user = super(RegistrationForm, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True}),
    )
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

class EditUserInfoForm(forms.ModelForm):
    city = forms.CharField(widget = forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'city...',
        }
    ))
    website = forms.URLField(widget = forms.URLInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'website...'
        }
    ))
    phone = forms.IntegerField(widget = forms.NumberInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'phone...'
        }
    ))
    profile_image = forms.ImageField()
    

    class Meta:
        model = UserProfile
        fields = (
            'city',
            'website',
            'phone',
            'profile_image',
        )
          

    

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from accounts.forms import (
        RegistrationForm, 
        EditProfileForm,
        EditUserInfoForm
)
from accounts.models import UserProfile

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance = request.user)

        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


class EditUserInfo(TemplateView):
    template_name = 'accounts/edit_user_info.html'

    def get(self, request):
        form = EditUserInfoForm()
        posts = UserProfile.city

        args = {'form': form, 'posts': posts}
        return render(request, self.template_name, args)

    def post(self, request):
        profile = request.user.userprofile
        form = EditUserInfoForm(request.POST, instance = profile)
        if form.is_valid():
            post = form.save(commit = False)
            post.user = request.user
            post.save()

            city = form.cleaned_data['city']
            website = form.cleaned_data['website']
            phone = form.cleaned_data['phone']
            profile_image = form.cleaned_data['profile_image']
            form =  EditUserInfoForm()
            return redirect('accounts:view_profile')

        args = {
            'form': form, 
            'city': city,
            'website': website,
            'profile_image': profile_image,
        }
        return render(request, self.template_name, args)   

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user = request.user)
        
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user = request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Password change</title>
{% endblock %}

{% block body %}

<!--
<div class = "container">
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit">Submit</button>
    </form>
</div>
-->

{% load widget_tweaks %}

<div class="form-div">
<br>
<h3>Change your password</h3>
<form method="post">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Edit profile</title>
{% endblock %}

{% block body %}

<!--
<div class = "container">
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit">Submit</button>
    </form>
</div>
-->

{% load widget_tweaks %}

<br>
<div class="row">
<div class="col-2">
    <div class="row"><h5 >Edit you profile</h5></div>
    
    <div class="row"><a  href="{% url 'accounts:edit_profile' %}">Profile Info</a></div>
    <div class="row"><a  href="{% url 'accounts:edit_user_info' %}">User Info</a></div>
    

</div>

<div class="col-6">
    <form method="post">
        {% csrf_token %}
    
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
    
        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</div>

{% endblock %}

accounts/templates/accounts/edit_user_info.html
{% extends 'base.html' %}

{% block head %}
<title>Edit profile</title>
{% endblock %}

{% block body %}

<!--
<div class = "container">
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type = "submit">Submit</button>
    </form>
</div>
-->

{% load widget_tweaks %}

<br>
<div class="row">
<div class="col-2">
    <div class="row"><h5 >Edit you profile</h5></div>
    
    <div class="row"><a  href="{% url 'accounts:edit_profile' %}">Profile Info</a></div>
    <div class="row"><a  href="{% url 'accounts:edit_user_info' %}">User Info</a></div>
    

</div>

<div class="col-6">
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}     
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
<title>Log in</title>
{% endblock %}

{% block body %}

{% load widget_tweaks %}
<br>
<div class="login-form">
<div class="main-div">
<div class="dropdown">
    <form method="post">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                <label class="form-check-label" for="dropdownCheck">
                    Remember me
                </label>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Log in</button>
    </form>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'accounts:register'%}">New around here? Sign up</a>
    <a class="dropdown-item" href="{% url 'accounts:password_reset'%}">Forgot password?</a>
</div>
</div>
</div>

{% endblock %}

<!--

    <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                    <label class="form-check-label" for="dropdownCheck">
                        Remember me
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
        </form>

-->

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Log out</title>
{% endblock %}

{% block body %}
<div class = "container">
    <h3>Logged Out! </h3>
    <a>You have logged out! </a>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Password Reset Complete</title>
{% endblock %}

{% block body %}
<div class = "container">
    <h3>Password Reset Complete </h3>
    <p>Your password has been set.  
        You may go ahead and log in now.</p>
    <a href="{% url 'accounts:login' %}">Log in</a>

</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block head %}
<title>Password Reset Confirm</title>
{% endblock %}

{% block body %}
<div class = "container">
    <h3>Password Reset Confirm</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>

</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block head %}
<title>Password Reset Done</title>
{% endblock %}

{% block body %}
<div class = "container">
    <h3>Password Reset Done </h3>
    <p>We've emailed you instructions for setting your password, 
        if an account exists with the email you entered. 
        You should receive them shortly.</p>
    <p>If you don't receive an email, 
        please make sure you've entered the address you registered with, 
        and check your spam folder.</p>

</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
 	
{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="row">
        <div class="col-lg-4">

        </div>
    <div class="col-lg-4">
        <div class="card" style="width:100%">
            <img class="card-img-top" src="{{ user.userprofile.profile_image.url }}" alt="Card image"  style="width:100%">
            <div class="card-body">
                <h4 class="card-title">{{ user }}</h4>
                    <ul class="list-inline" id="courses">
                        <li class="list-inline-item">
                            <i class="fa fa-folder-open-o"></i> Network administrator
                        </li>
                    </ul>
                    <p class="card-text">{{ user.userprofile.description }}</p>

                <div class="address">								
                    <ul class="w3-ul w3-small">
                        <li><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ user.first_name}} {{ user.last_name}}</li>
                        <li><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ user.email}}</li>
                        <li><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ user.userprofile.city}}</li>
                        <li><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ user.userprofile.phone}}</li>
                        <li><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ user.userprofile.website}}</li>
                    </ul>
                    </address>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block body %}
<!--
<div class = "container">
    <h1>Register<br></h1>
    <form method="post">
        {% csrf_token %}
        <table border="1">
            {{ form }}
        </table>
        <button type = "submit">Submit</button>
    </form>
</div>
-->

{% load widget_tweaks %}


<div class="form-div">
    <br>
    <h3>Register</h3>
    <form method="post">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
<!-- djangoproject -->

{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
{% endblock %}

{% block body %}

<!--
<div class = "container">
    <h1>Password reset </h1>
    <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Reset password</button>
    </form>
</div>
-->

{% load widget_tweaks %}

<div class="form-div">
    <br>
    <h3>Password reset</h3>
    <form method="post">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Reset password</button>
    </form>
</div>

{% endblock %}