accounts/urls.py
from django.urls import path, re_path, reverse, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)

from . import views
from accounts.views import EditUserInfo

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name = 'logout'),
    path('register/', views.register, name = 'register'),
    path('profile/', views.view_profile, name = 'view_profile'),
    path('profile/edit/', views.edit_profile, name = 'edit_profile'),
    path('profile/edit/user_info', EditUserInfo.as_view(), name = 'edit_user_info'),
    path('change-password/', views.change_password, name = 'change_password'),
    
    path('reset-password/', PasswordResetView.as_view(
        template_name = 'accounts/reset_password.html',
        success_url = reverse_lazy('accounts:password_reset_done'),
        email_template_name = 'accounts/password_reset_email.html'), 
        name='password_reset'
    ),
    path('reset-password/done/', PasswordResetDoneView.as_view(
       template_name = 'accounts/password_reset_done.html', ), 
       name='password_reset_done'
    ),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name = 'accounts/password_reset_confirm.html', 
        success_url = reverse_lazy('accounts:password_reset_complete'),),
        name='password_reset_confirm'
    ),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(
        template_name = 'accounts/password_reset_complete.html', ), 
        name='password_reset_complete'
    ),

]

blog/urls.py
from django.urls import path

from blog.views import BlogHomeView,PublishPostView

app_name = 'blog'
urlpatterns = [
    path('', BlogHomeView.as_view(), name = 'blogHome'),
    path('publish/', PublishPostView.as_view(), name = 'publish_post'),
    
]

home/urls.py
from django.urls import path

from home.views import HomeView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    
]

loginSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('account/', include('accounts.urls')),
    path('home/', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    profile_image = models.ImageField(upload_to = 'profile_image', blank = True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])

post_save.connect(create_profile, sender = User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    UserCreationForm, 
    UserChangeForm,
)

from accounts.models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
    def save(self, commit = True):
        user = super(RegistrationForm, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True}),
    )
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

class EditUserInfoForm(forms.ModelForm):
    city = forms.CharField(widget = forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'city...',
        }
    ))
    website = forms.URLField(widget = forms.URLInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'website...'
        }
    ))
    phone = forms.IntegerField(widget = forms.NumberInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'phone...'
        }
    ))
    profile_image = forms.ImageField()
    

    class Meta:
        model = UserProfile
        fields = (
            'city',
            'website',
            'phone',
            'profile_image',
        )
          

    

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic import TemplateView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from accounts.forms import (
        RegistrationForm, 
        EditProfileForm,
        EditUserInfoForm
)
from accounts.models import UserProfile

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance = request.user)

        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


class EditUserInfo(TemplateView):
    template_name = 'accounts/edit_user_info.html'

    def get(self, request):
        form = EditUserInfoForm()
        posts = UserProfile.city

        args = {'form': form, 'posts': posts}
        return render(request, self.template_name, args)

    def post(self, request):
        profile = request.user.userprofile
        form = EditUserInfoForm(request.POST, instance = profile)
        if form.is_valid():
            post = form.save(commit = False)
            post.user = request.user
            post.save()

            city = form.cleaned_data['city']
            website = form.cleaned_data['website']
            phone = form.cleaned_data['phone']
            profile_image = form.cleaned_data['profile_image']
            form =  EditUserInfoForm()
            return redirect('accounts:view_profile')

        args = {
            'form': form, 
            'city': city,
            'website': website,
            'profile_image': profile_image,
        }
        return render(request, self.template_name, args)   

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user = request.user)
        
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user = request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" 
            rel="stylesheet" 
            integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" 
            crossorigin="anonymous">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" 
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" 
            crossorigin="anonymous">   
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" 
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" 
            crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" 
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" 
            crossorigin="anonymous">
        </script>    
        {% load static %}
        <link rel="stylesheet" href="{% static 'accounts/style.css'%}">
        <style>
            .fakeimg {
                height: 200px;
                background: #aaa;
            }
        </style>
        {% block head %}
        {% endblock %}
    </head>

    <body>
        <div class="jumbotron">
           <!-- <img src="{% static '/image/siteimg.jpg' %}" width="240"> -->
            <h1>Space Linkers</h1>
            <p>This is my site!</p> 
        </div>
 
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SpaceLinkers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home:home' %}">Home </a>
                            <span class="sr-only">(current)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile </a>
                        </li>    
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{user}}
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                                <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile </a>
                                <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password </a>
                            </div>
                        </div>
                    </ul>

                    {% else %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blogHome' %}">Blog </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register </a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container">
            <br>
            {% block body %}
            {% endblock %}
            <br>
        </div>

        <footer class="footer p-t-1" >
            
                <a href="#"><i class="fa fa-facebook-official fa-2x"></i></a>
                <a href="#"><i class="fa fa-pinterest-p fa-2x"></i></a>
                <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                <a href="#"><i class="fa fa-flickr fa-2x"></i></a>
                <a href="#"><i class="fa fa-linkedin fa-2x"></i></a>
    
                <p class="h6">
                    @all right reserved by Hasan
                </p>
            
        </footer>
    </body>
</html>